CFLAGS = -Wall -ggdb
CC = gcc
SRCS = echo arguments generator factorial nested delay

all: $(SRCS)
echo: echo.c
arguments: arguments.c
generator: generator.c
factorial: factorial.c
nested: nested.c
delay: delay.c

clean:
	$(RM) $(SRCS)
