CFLAGS = -Wall -ggdb
CC = gcc
SRCS = echo arguments generator factorial nested delay spsc password

all: $(SRCS)
echo: echo.c
arguments: arguments.c
generator: generator.c
factorial: factorial.c
nested: nested.c
delay: delay.c
spsc: spsc.c
password: password.c

clean:
	$(RM) $(SRCS)
